# Generated by Django 3.1.7 on 2021-04-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0002_auto_20210404_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
