# Generated by Django 3.1.7 on 2021-04-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0004_auto_20210405_0912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoMarkSMS',
            new_name='AutoMarkMessage',
        ),
    ]
