# Generated by Django 3.1.7 on 2021-04-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0005_auto_20210405_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFastMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=320, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinPartsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=320, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
