# Generated by Django 3.1.7 on 2021-04-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0006_autofastmessage_winpartsmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automarkmessage',
            old_name='count',
            new_name='custcount',
        ),
        migrations.AddField(
            model_name='automarkmessage',
            name='msgcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
