# Generated by Django 3.1.7 on 2021-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0007_auto_20210419_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autofastmessage',
            old_name='count',
            new_name='custcount',
        ),
        migrations.RenameField(
            model_name='winpartsmessage',
            old_name='count',
            new_name='custcount',
        ),
        migrations.AddField(
            model_name='autofastmessage',
            name='msgcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='winpartsmessage',
            name='msgcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
