# Generated by Django 3.1.7 on 2021-04-20 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0010_auto_20210419_2021'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autofastmessage',
            table='bulksms_autofastmessage',
        ),
    ]
