# Generated by Django 3.1.7 on 2021-04-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulksms', '0011_auto_20210420_0605'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='autofastmessage',
            table=None,
        ),
    ]
