# Generated by Django 3.1.7 on 2021-04-22 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulksms', '0012_auto_20210420_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=320, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('msgcount', models.IntegerField(blank=True, null=True)),
                ('custcount', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoFastTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, null=True)),
                ('message', models.CharField(max_length=320, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('msgcount', models.IntegerField(blank=True, null=True)),
                ('custcount', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
